import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import type { IBio } from '../src/content/bio'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const BIOS_DIR = join(ROOT, 'content/bios')
const OUT = join(ROOT, 'src/generated/icons.ts')

const names = new Set<string>(['mdi:export-variant'])
for (const file of readdirSync(BIOS_DIR).filter((f) => f.endsWith('.json'))) {
  const bio = JSON.parse(readFileSync(join(BIOS_DIR, file), 'utf8')) as IBio
  for (const link of [...bio.links, ...bio.socials]) {
    if (link.icon) {
      names.add(link.icon)
    }
  }
}

const map: Record<string, string> = {}
for (const name of [...names].sort()) {
  try {
    const res = await fetch(`https://api.iconify.design/${name}.svg`)
    if (!res.ok) {
      console.warn(`[icons] skip ${name}: HTTP ${res.status}`)
      continue
    }
    const svg = (await res.text()).trim()
    const encoded = encodeURIComponent(svg).replace(/\(/g, '%28').replace(/\)/g, '%29')
    map[name] = `data:image/svg+xml,${encoded}`
  } catch (err) {
    console.warn(`[icons] skip ${name}: ${err}`)
  }
}

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/generate-icons.ts — do not edit.\n` +
    `export const ICONS: Record<string, string> = ${JSON.stringify(map, null, 2)}\n`,
)
console.log(`[icons] inlined ${Object.keys(map).length} icon(s) -> src/generated/icons.ts`)
